[versions]
compileSdk = "34"
minSdk = "24"

agp = "8.6.0"
kotlin = "2.0.20"
ksp = "2.0.20-1.0.25"

wire = "5.1.0"

hilt = "2.52"

activity = "1.9.2"
fragment-ktx = "1.8.3"
core-ktx = "1.13.1"
appcompat = "1.7.0"
datastore = "1.1.1"
constraintlayout = "2.1.4"
recyclerview = "1.3.2"
webkit = "1.11.0"
material = "1.12.0"
lifecycle = "2.8.5"
room = "2.6.1"

okhttp = "5.0.0-alpha.14"
retrofit = "2.11.0"
okio = "3.9.0"
moshi = "1.15.1"
coil = "2.7.0"
kotlinx-coroutines = "1.9.0-RC.2"

compose-bom = "2024.09.01"

constraintlayout-compose = "1.0.1"
navigation-compose = "2.8.0"

glance = "1.1.0"
leakcanary = "3.0-alpha-8"
chuckerteam = "4.0.0"

hamcrest = "3.0"
junit = "4.13.2"

mockk = "1.13.12"
androidx-test-ext-junit = "1.2.1"
espresso-core = "3.6.1"

[libraries]
#   官方依赖库
fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "fragment-ktx" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }

constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
webkit = { group = "androidx.webkit", name = "webkit", version.ref = "webkit" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

#lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
#lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }

room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }

#   三方依赖库
okhttp3 = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
okhttp3-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }
retrofit2 = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit2-moshi = { group = "com.squareup.retrofit2", name = "converter-moshi", version.ref = "retrofit" }
okio = { group = "com.squareup.okio", name = "okio", version.ref = "okio" }

moshi = { group = "com.squareup.moshi", name = "moshi", version.ref = "moshi" }
moshi-kotlin-codegen = { group = "com.squareup.moshi", name = "moshi-kotlin-codegen", version.ref = "moshi" }
wire-moshi-adapter = { group = "com.squareup.wire", name = "wire-moshi-adapter", version.ref = "wire" }


coil = { group = "io.coil-kt", name = "coil", version.ref = "coil" }

kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }

#   compose依赖库
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
ui = { group = "androidx.compose.ui", name = "ui" }
ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-material = { group = "androidx.compose.material", name = "material" }
material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }
#compose-material3 = { group = "androidx.compose.material3", name = "material3", version = "1.2.0" }

ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }

lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycle" }
lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle" }

constraintlayout-compose = { group = "androidx.constraintlayout", name = "constraintlayout-compose", version.ref = "constraintlayout-compose" }
navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation-compose" }

coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }

# Debug依赖库
glance = { group = "com.guolindev.glance", name = "glance", version.ref = "glance" }
leakcanary-android = { group = "com.squareup.leakcanary", name = "leakcanary-android", version.ref = "leakcanary" }
chuckerteam = { group = "com.github.chuckerteam.chucker", name = "library", version.ref = "chuckerteam" }
chuckerteam-no-op = { group = "com.github.chuckerteam.chucker", name = "library-no-op", version.ref = "chuckerteam" }

# 测试依赖库
hamcrest = { group = "org.hamcrest", name = "hamcrest", version.ref = "hamcrest" }
hamcrest-library = { group = "org.hamcrest", name = "hamcrest-library", version.ref = "hamcrest" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }

androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }

# -------------- hilt 代支持ksp 再合并 ----------------
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version = "1.2.0" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

wire = { id = "com.squareup.wire", version.ref = "wire" }

compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }

[bundles]
network = ["okhttp3", "okhttp3-logging-interceptor", "retrofit2", "retrofit2-moshi", "okio"]
testBundle = ["hamcrest", "hamcrest-library", "junit", "mockk"]
androidTestBundle = ["androidx-test-ext-junit", "espresso-core"]
